import type { FilesAPI } from '@/lib/api/types';
import type { RepoIndex } from '@/lib/repoIndex/schema';

export const PROJECT_DOCS_DIRECTORY = 'docs';
export const PROJECT_DOCS_FILE_NAME = 'PROJECT_DOCS.md';

const normalizeRoot = (projectRoot: string): string => projectRoot.replace(/\\/g, '/').replace(/\/+$/, '');

export const buildProjectDocsPath = (projectRoot: string): string => {
  const root = normalizeRoot(projectRoot.trim());
  return root ? `${root}/${PROJECT_DOCS_DIRECTORY}/${PROJECT_DOCS_FILE_NAME}` : `${PROJECT_DOCS_DIRECTORY}/${PROJECT_DOCS_FILE_NAME}`;
};

export const buildProjectDocsDirectoryPath = (projectRoot: string): string => {
  const root = normalizeRoot(projectRoot.trim());
  return root ? `${root}/${PROJECT_DOCS_DIRECTORY}` : PROJECT_DOCS_DIRECTORY;
};

const listItems = (items: string[], empty = '- none detected'): string => (items.length ? items.map((item) => `- ${item}`).join('\n') : empty);

export const renderProjectDocsMarkdown = (index: RepoIndex, projectRoot: string): string => {
  const generatedAt = new Date(index.generatedAt).toLocaleString();
  const docsFiles = index.files.filter((file) => file.isDocs).slice(0, 30).map((file) => file.path);
  const packages = index.packageBoundaries.slice(0, 30).map((pkg) => pkg.name || pkg.path || 'repo root');
  const largestSourceFiles = [...index.files]
    .filter((file) => !file.isDocs && file.language !== 'other')
    .sort((a, b) => b.size - a.size)
    .slice(0, 30)
    .map((file) => `${file.path} (${file.language}, ${file.size} bytes)`);
  const symbols = index.symbols
    .slice(0, 80)
    .map((symbol) => `${symbol.kind} ${symbol.name} — ${symbol.path}:${symbol.line}`);

  return [
    '# Project Docs',
    '',
    '<!-- Generated by DevChamber. Edit freely; this file is stored in the repository docs folder so Repo Docs survives VS Code restarts. -->',
    '',
    `Workspace: ${projectRoot || 'current workspace'}`,
    `Generated: ${generatedAt}`,
    '',
    '## Repository scan',
    '',
    `- Files: ${index.files.length}`,
    `- Directories: ${index.directories.length}`,
    `- Symbols: ${index.symbols.length}`,
    `- Existing docs files: ${index.docsFiles.length}`,
    `- Package boundaries: ${index.packageBoundaries.length}`,
    index.ignoredCount > 0 ? `- Ignored/skipped files: ${index.ignoredCount}` : null,
    '',
    '## Existing documentation',
    '',
    listItems(docsFiles),
    '',
    '## Main packages',
    '',
    listItems(packages),
    '',
    '## Source files to inspect first',
    '',
    listItems(largestSourceFiles),
    '',
    '## Indexed symbols sample',
    '',
    listItems(symbols),
    '',
    '## Agent instructions',
    '',
    'Improve this file into user-facing project documentation. Explain what the project is, how it is structured, key modules, important flows, setup/run hints inferred from files, and documentation gaps. Keep concrete file references.',
    '',
  ].filter((line): line is string => line !== null).join('\n');
};

export const saveProjectDocsFile = async ({
  files,
  index,
  projectRoot,
}: {
  files: Pick<FilesAPI, 'createDirectory' | 'writeFile'>;
  index: RepoIndex;
  projectRoot: string;
}): Promise<{ path: string }> => {
  if (!files.writeFile) {
    throw new Error('Project docs persistence is not available in this runtime.');
  }

  const directory = buildProjectDocsDirectoryPath(projectRoot);
  if (files.createDirectory) {
    await files.createDirectory(directory);
  }

  const path = buildProjectDocsPath(projectRoot);
  await files.writeFile(path, renderProjectDocsMarkdown(index, projectRoot));
  return { path };
};
